### ISSUE TITLE
[R2]: PreSigned URLS now implemented

### ISSUE THREAD

**Issue by waptik** [skymethod/denoflare-docs#3]
It seems like pre-signed urls have been implemented in r2. So R2 buckets now natively support them. See https://discord.com/channels/595317990191398933/940663374377783388/993176081089699910

**Comment by johnspurlock-skymethod** [comment]
Good point - I should remove the presigned url example worker doc, since it's no longer strictly needed.

Also should create a `denoflare r2 presign` command to generate native r2 presigned urls.

I'll add this in the next minor update

**Comment by waptik** [comment]
I'm looking forward to seeing how it goes. I wanted to give denoflare a go today for my r2 bucket but saw that I needed two workers(1 for presigned urls, 1 for pubic files). So I decided to forgo that notion, and give you a heads up.

**Comment by johnspurlock-skymethod** [comment]
Just published a new Denoflare release [v0.5.3](https://github.com/skymethod/denoflare/releases/tag/v0.5.3) that has a new r2 subcommand (`denoflare r2 presign`) for generating native r2 presigned urls ([docs](https://denoflare.dev/cli/r2#presign))

Also removed the obsolete denoflare helper worker example from the docs page, although the code is still in the repo if anyone wants to use it to obscure their real access keys, or use it as a starting point for a custom presigned url worker.
