### ISSUE TITLE
R2 can already be publicly assessible now.

### ISSUE THREAD

**Issue by Chinoman10** [skymethod/denoflare-docs#5]
Regarding this page: https://github.com/skymethod/denoflare-docs/blob/HEAD/examples/r2-public-read.md

R2 buckets can be made publicly accessible through the CF Dashboard now:
![image](https://user-images.githubusercontent.com/8300763/192284566-c340c68d-47c7-4fb8-bbab-924904de4045.png)

So the docs need to be updated (as it implies that there's no way to make the buckets available without deploying a worker).

**Comment by johnspurlock-skymethod** [comment]
Agreed - very happy that this is supported natively now.  I'll update the docs today

**Comment by johnspurlock-skymethod** [comment]
Ok, new docs are live
